import { Liability } from "@/lib/types";

export const sampleLiabilities: Liability[] = [
  {
    id: "1",
    userId: "sample_user_1",
    name: "Home Mortgage",
    category: "Mortgage",
    currentValue: 450000,
    currency: "AUD",
    institution: "Commonwealth Bank",
    changeAmount: -50000,
    changePercentage: -10.0,
    isActive: true,
    createdAt: "2020-06-15",
    updatedAt: "2024-11-15",
  },
  {
    id: "2",
    userId: "sample_user_1",
    name: "Car Loan",
    category: "Vehicle Loan",
    currentValue: 25000,
    currency: "AUD",
    institution: "Westpac",
    changeAmount: -3000,
    changePercentage: -10.7,
    isActive: true,
    createdAt: "2022-03-10",
    updatedAt: "2024-11-15",
  },
  {
    id: "3",
    userId: "sample_user_1",
    name: "Credit Card Debt",
    category: "Credit Card",
    currentValue: 8500,
    currency: "AUD",
    institution: "ANZ",
    changeAmount: 500,
    changePercentage: 6.25,
    isActive: true,
    createdAt: "2023-01-15",
    updatedAt: "2024-11-15",
  },
  {
    id: "4",
    userId: "sample_user_1",
    name: "Personal Loan",
    category: "Personal Loan",
    currentValue: 12000,
    currency: "AUD",
    institution: "NAB",
    changeAmount: -2000,
    changePercentage: -14.3,
    isActive: true,
    createdAt: "2023-08-20",
    updatedAt: "2024-11-15",
  },
  {
    id: "5",
    userId: "sample_user_1",
    name: "Student Loan",
    category: "Education Loan",
    currentValue: 35000,
    currency: "AUD",
    institution: "Government",
    changeAmount: -5000,
    changePercentage: -12.5,
    isActive: true,
    createdAt: "2019-02-01",
    updatedAt: "2024-11-15",
  },
  {
    id: "6",
    userId: "sample_user_1",
    name: "Business Loan",
    category: "Business Loan",
    currentValue: 75000,
    currency: "AUD",
    institution: "Commonwealth Bank",
    changeAmount: -10000,
    changePercentage: -11.8,
    isActive: true,
    createdAt: "2021-05-10",
    updatedAt: "2024-11-15",
  },
  {
    id: "7",
    userId: "sample_user_1",
    name: "Line of Credit",
    category: "Line of Credit",
    currentValue: 15000,
    currency: "AUD",
    institution: "Westpac",
    changeAmount: 2000,
    changePercentage: 15.4,
    isActive: true,
    createdAt: "2022-11-01",
    updatedAt: "2024-11-15",
  },
  {
    id: "8",
    userId: "sample_user_1",
    name: "Investment Property Loan",
    category: "Mortgage",
    currentValue: 320000,
    currency: "AUD",
    institution: "ANZ",
    changeAmount: -15000,
    changePercentage: -4.5,
    isActive: true,
    createdAt: "2020-09-15",
    updatedAt: "2024-11-15",
  },
  {
    id: "9",
    userId: "sample_user_1",
    name: "Paid Off Car Loan",
    category: "Vehicle Loan",
    currentValue: 0,
    currency: "AUD",
    institution: "NAB",
    changeAmount: -18000,
    changePercentage: -100.0,
    isActive: false,
    createdAt: "2021-01-15",
    updatedAt: "2024-10-15",
  },
  {
    id: "10",
    userId: "sample_user_1",
    name: "Credit Card Balance Transfer",
    category: "Credit Card",
    currentValue: 4200,
    currency: "AUD",
    institution: "Commonwealth Bank",
    changeAmount: -800,
    changePercentage: -16.0,
    isActive: true,
    createdAt: "2024-06-01",
    updatedAt: "2024-11-15",
  },
];
