import { Asset } from "@/lib/types";

export const sampleAssets: Asset[] = [
  {
    id: "1",
    name: "Savings Account",
    category: "Savings Account",
    value: 15420,
    currency: "AUD",
    institution: "Bank of Australia",
    accountNumber: "****1234",
    currentValue: 15420,
    changeAmount: 320,
    changePercentage: 2.1,
    notes: "High-yield savings account",
    isActive: true,
    createdAt: "2024-01-01",
    updatedAt: "2024-11-15",
  },
  {
    id: "2",
    name: "Investment Portfolio",
    category: "Investment Account",
    value: 42800,
    currency: "AUD",
    institution: "Vanguard 401(k)",
    accountNumber: "****5678",
    currentValue: 42800,
    changeAmount: 3400,
    changePercentage: 8.5,
    notes: "Diversified investment portfolio",
    isActive: true,
    createdAt: "2024-01-01",
    updatedAt: "2024-11-15",
  },
  {
    id: "3",
    name: "Home Equity",
    category: "Real Estate",
    value: 125000,
    currency: "AUD",
    institution: "Primary Residence",
    purchaseDate: "2020-06-15",
    currentValue: 125000,
    changeAmount: 6200,
    changePercentage: 5.2,
    notes: "Family home in Sydney",
    isActive: true,
    createdAt: "2020-06-15",
    updatedAt: "2024-11-15",
  },
  {
    id: "4",
    name: "Emergency Fund",
    category: "Savings Account",
    value: 8500,
    currency: "AUD",
    institution: "High-Yield Savings",
    accountNumber: "****9012",
    currentValue: 8500,
    changeAmount: 310,
    changePercentage: 3.8,
    notes: "Emergency fund for unexpected expenses",
    isActive: true,
    createdAt: "2024-01-01",
    updatedAt: "2024-11-15",
  },
  {
    id: "5",
    name: "Car",
    category: "Vehicle",
    value: 25000,
    currency: "AUD",
    institution: "Personal Vehicle",
    purchaseDate: "2022-03-10",
    currentValue: 22000,
    changeAmount: -3000,
    changePercentage: -12.0,
    notes: "2022 Toyota Camry",
    isActive: true,
    createdAt: "2022-03-10",
    updatedAt: "2024-11-15",
  },
  {
    id: "6",
    name: "Retirement Fund",
    category: "Retirement Account",
    value: 67500,
    currency: "AUD",
    institution: "Superannuation Fund",
    accountNumber: "****3456",
    currentValue: 67500,
    changeAmount: 5200,
    changePercentage: 8.3,
    notes: "Employer-sponsored retirement plan",
    isActive: true,
    createdAt: "2018-01-01",
    updatedAt: "2024-11-15",
  },
  {
    id: "7",
    name: "Cryptocurrency Portfolio",
    category: "Cryptocurrency",
    value: 3200,
    currency: "AUD",
    institution: "Digital Wallet",
    purchaseDate: "2023-08-20",
    currentValue: 3200,
    changeAmount: 800,
    changePercentage: 33.3,
    notes: "Bitcoin and Ethereum holdings",
    isActive: true,
    createdAt: "2023-08-20",
    updatedAt: "2024-11-15",
  },
  {
    id: "8",
    name: "Jewelry Collection",
    category: "Jewelry",
    value: 8500,
    currency: "AUD",
    institution: "Personal Collection",
    purchaseDate: "2021-12-25",
    currentValue: 8500,
    changeAmount: 500,
    changePercentage: 6.3,
    notes: "Family heirloom and investment pieces",
    isActive: true,
    createdAt: "2021-12-25",
    updatedAt: "2024-11-15",
  },
];
